import { useEffect,useRef,useState } from 'react';
import { CalendarDays,ClipboardCheck,Gift } from 'lucide-react';
import { api } from '../api';
import { isoDate } from '../dates';
import type { Dashboard,Student } from '../types';

export function DashboardPage({student,onNavigate}:{student:Student;onNavigate:(page:'today'|'week'|'rewards')=>void}){
 const[dashboard,setDashboard]=useState<Dashboard|null>(null),[error,setError]=useState('');
 const requestVersion=useRef(0);
 useEffect(()=>{const version=++requestVersion.current;setDashboard(null);setError('');api<{dashboard:Dashboard}>(`/api/students/${student.id}/dashboard?date=${isoDate()}`).then(result=>{if(version===requestVersion.current)setDashboard(result.dashboard)}).catch(reason=>{if(version===requestVersion.current)setError(reason.message)})},[student.id]);
 const rate=dashboard?.todayCompletionRate;const rateText=rate===null||rate===undefined?'—':`${Math.round(rate*100)}%`;
 return <><div className="page-heading"><div><span className="eyebrow">数据概览</span><h1>{student.name}的学习工作台</h1><p>{student.school||'学校未填写'} · {student.grade||'年级未填写'}</p></div><div className="date-chip">{new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(new Date())}</div></div>{error&&<p className="error">{error}</p>}{dashboard?.empty?<div className="empty-state"><h2>还没有可统计的学习数据</h2><p>先为这个孩子安排今日任务或产生积分流水后，这里会显示完成情况和积分变化，而不是错误趋势。</p><button className="primary" onClick={()=>onNavigate('week')}><CalendarDays size={18}/>制定周计划</button></div>:dashboard&&<><div className="metrics"><article><span>今日任务</span><strong>{dashboard.planned+dashboard.submitted+dashboard.evaluated}</strong><small>未开始 {dashboard.planned} · 已提交 {dashboard.submitted} · 已评价 {dashboard.evaluated} · 已完成 {dashboard.completed}</small></article><article><span>今日完成率</span><strong>{rateText}</strong><small>按已完成 / 今日任务计算</small></article><article><span>积分余额</span><strong>{dashboard.pointsBalance}</strong><small>今日 +{dashboard.todayEarned} / -{dashboard.todaySpent} · 本周 +{dashboard.weekEarned} / -{dashboard.weekSpent}</small></article></div><div className="workspace"><section className="panel"><div className="panel-head"><div><span className="eyebrow">本周趋势</span><h2>每日基础完成率</h2></div></div><div className="trend">{dashboard.weekTrend.map(day=><div key={day.date}><span>{day.date.slice(5)}</span><strong>{day.completionRate===null?'—':`${Math.round(day.completionRate*100)}%`}</strong></div>)}</div></section><section className="panel next"><span className="eyebrow">继续处理</span><h2>进入对应页面</h2><p>从概览跳到今日看板或积分奖励，数据始终只统计当前孩子。</p><div className="stack-actions"><button className="primary" onClick={()=>onNavigate('today')}><ClipboardCheck size={18}/>今日看板</button><button className="secondary" onClick={()=>onNavigate('rewards')}><Gift size={18}/>积分奖励</button></div></section></div></>}</>
}
