import { useEffect,useRef,useState } from 'react';
import { CirclePlus,X } from 'lucide-react';
import { api } from '../api';
import { useSubjectCatalog } from '../subject-catalog';
import { mistakeReasons,redoStatuses,type Mistake,type Subject } from '../types';

const empty={subject:'math' as Subject,summary:'',reason:'concept',reasonNote:'',correctSolution:'',redoStatus:'not_redone'};
export function MistakesPage({studentId}:{studentId:number}){
 const{subjects,label:subjectLabel}=useSubjectCatalog();
 const[mistakes,setMistakes]=useState<Mistake[]>([]),[filter,setFilter]=useState<Subject|'all'>('all'),[form,setForm]=useState(empty),[files,setFiles]=useState<FileList|null>(null),[editing,setEditing]=useState<Mistake|null>(null),[modal,setModal]=useState(false),[error,setError]=useState('');
 const requestVersion=useRef(0);
 async function load(){const version=++requestVersion.current;const query=filter==='all'?'':`?subject=${filter}`;try{const result=await api<{mistakes:Mistake[]}>(`/api/students/${studentId}/mistakes${query}`);if(version===requestVersion.current)setMistakes(result.mistakes)}catch(reason){setError(reason instanceof Error?reason.message:'读取失败')}}
 useEffect(()=>{setMistakes([]);void load()},[studentId,filter]);
 async function save(event:React.FormEvent){event.preventDefault();try{if(editing){await api(`/api/students/${studentId}/mistakes/${editing.id}`,{method:'PUT',body:JSON.stringify(form)})}else{const data=new FormData();for(const [key,value] of Object.entries(form))data.set(key,value);if(files)for(const file of files)data.append('photos',file);await api(`/api/students/${studentId}/mistakes`,{method:'POST',body:data})}setModal(false);setFiles(null);await load()}catch(reason){setError(reason instanceof Error?reason.message:'保存失败')}}
 async function remove(mistake:Mistake){if(!confirm(`删除“${mistake.summary}”？`))return;await api(`/api/students/${studentId}/mistakes/${mistake.id}`,{method:'DELETE'});await load()}
 return <><div className="page-heading"><div><span className="eyebrow">Mistake Notebook</span><h1>错题本</h1><p>按科目记录错题、原因和照片。第一版不自动生成重做任务。</p></div><button className="primary" onClick={()=>{setEditing(null);setForm(empty);setFiles(null);setModal(true)}}><CirclePlus size={18}/>新增错题</button></div>{error&&<p className="error">{error}</p>}<div className="board-layout"><aside className="subject-filter"><strong>科目筛选</strong><button className={filter==='all'?'selected':''} onClick={()=>setFilter('all')}>全部</button>{subjects.map(subject=><button className={filter===subject.id?'selected':''} key={subject.id} onClick={()=>setFilter(subject.id)}>{subject.label}</button>)}</aside><section className="card-list">{mistakes.length?mistakes.map(mistake=><article key={mistake.id}><div><span className="subject-badge">{subjectLabel(mistake.subject)}</span><h3>{mistake.summary}</h3><p>{mistakeReasons.find(item=>item.id===mistake.reason)?.label}{mistake.reasonNote?` · ${mistake.reasonNote}`:''}</p><p>{mistake.correctSolution||'尚未填写正确解法'} · {redoStatuses.find(item=>item.id===mistake.redoStatus)?.label}</p>{mistake.photos.map(photo=><img alt={photo.originalFilename} key={photo.id} src={`/api/students/${studentId}/photos/${photo.id}`}/>)}</div><div className="stack-actions"><button className="text-button" onClick={()=>{setEditing(mistake);setForm({subject:mistake.subject,summary:mistake.summary,reason:mistake.reason,reasonNote:mistake.reasonNote,correctSolution:mistake.correctSolution,redoStatus:mistake.redoStatus});setModal(true)}}>编辑</button><button className="text-button" onClick={()=>void remove(mistake)}>删除</button></div></article>):<div className="empty-board"><h2>还没有错题记录</h2><p>按科目录入题目摘要、错误原因和可选照片即可。</p></div>}</section></div>
 {modal&&<div className="backdrop"><form className="modal task-modal" onSubmit={save}><div className="modal-head"><div><span className="eyebrow">Mistake</span><h2>{editing?'编辑错题':'新增错题'}</h2></div><button className="icon-button" onClick={()=>setModal(false)} title="关闭" type="button"><X size={20}/></button></div><div className="form-row"><label>科目<select onChange={e=>setForm({...form,subject:e.target.value as Subject})} value={form.subject}>{subjects.map(subject=><option key={subject.id} value={subject.id}>{subject.label}</option>)}</select></label><label>错误原因<select onChange={e=>setForm({...form,reason:e.target.value})} value={form.reason}>{mistakeReasons.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label></div><label>题目摘要<input onChange={e=>setForm({...form,summary:e.target.value})} required value={form.summary}/></label><label>原因备注<input onChange={e=>setForm({...form,reasonNote:e.target.value})} value={form.reasonNote}/></label><label>正确解法<textarea onChange={e=>setForm({...form,correctSolution:e.target.value})} rows={3} value={form.correctSolution}/></label><label>重做状态<select onChange={e=>setForm({...form,redoStatus:e.target.value})} value={form.redoStatus}>{redoStatuses.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label>{!editing&&<label>题目照片<input accept="image/jpeg,image/png,image/webp,image/gif" multiple onChange={e=>setFiles(e.target.files)} type="file"/></label>}<div className="modal-actions"><button className="secondary" onClick={()=>setModal(false)} type="button">取消</button><button className="primary" type="submit">保存错题</button></div></form></div>}</>
}
