import { useEffect,useRef,useState } from 'react';
import { CirclePlus,X } from 'lucide-react';
import { api } from '../api';
import { rewardCategories,type Redemption,type Reward } from '../types';

const empty={name:'',category:'gift',requiredPoints:100,cashAmount:5,description:'',active:true};
export function RewardsPage({studentId}:{studentId:number}){
 const[rewards,setRewards]=useState<Reward[]>([]),[requests,setRequests]=useState<Redemption[]>([]),[balance,setBalance]=useState(0),[form,setForm]=useState(empty),[editing,setEditing]=useState<Reward|null>(null),[modal,setModal]=useState(false),[error,setError]=useState('');
 const requestVersion=useRef(0);
 async function load(){const version=++requestVersion.current;try{const [rewardResult,requestResult,points]=await Promise.all([api<{rewards:Reward[]}>(`/api/students/${studentId}/rewards`),api<{requests:Redemption[]}>(`/api/students/${studentId}/redemptions`),api<{balance:number}>(`/api/students/${studentId}/points`)]);if(version===requestVersion.current){setRewards(rewardResult.rewards);setRequests(requestResult.requests);setBalance(points.balance)}}catch(reason){setError(reason instanceof Error?reason.message:'读取失败')}}
 useEffect(()=>{setRewards([]);setRequests([]);setBalance(0);void load()},[studentId]);
 async function save(event:React.FormEvent){event.preventDefault();try{const payload={...form,cashAmount:form.category==='cash'?form.requiredPoints*5/100:null};await api(editing?`/api/students/${studentId}/rewards/${editing.id}`:`/api/students/${studentId}/rewards`,{method:editing?'PUT':'POST',body:JSON.stringify(payload)});setModal(false);await load()}catch(reason){setError(reason instanceof Error?reason.message:'保存失败')}}
 async function requestReward(reward:Reward){try{await api(`/api/students/${studentId}/redemptions`,{method:'POST',body:JSON.stringify({rewardId:reward.id})});await load()}catch(reason){setError(reason instanceof Error?reason.message:'申请失败')}}
 async function decide(id:number,action:'approve'|'reject'){try{await api(`/api/students/${studentId}/redemptions/${id}/${action}`,{method:'POST',body:JSON.stringify({note:action==='reject'?'暂不兑换':''})});await load()}catch(reason){setError(reason instanceof Error?reason.message:'审批失败')}}
 return <><div className="page-heading"><div><span className="eyebrow">Points and Rewards</span><h1>积分奖励</h1><p>申请时不扣分；家长批准后才从 Points Balance 扣除。</p></div><div className="heading-meta"><span className="balance-chip">积分余额 {balance}</span><button className="primary" onClick={()=>{setEditing(null);setForm(empty);setModal(true)}}><CirclePlus size={18}/>新增奖励</button></div></div>{error&&<p className="error">{error}</p>}<div className="split-panels"><section className="panel"><div className="panel-head"><h2>可用奖励</h2></div><div className="card-list">{rewards.length?rewards.map(reward=><article className={reward.active?'':'inactive'} key={reward.id}><div><strong>{reward.name}</strong><p>{rewardCategories.find(item=>item.id===reward.category)?.label} · {reward.requiredPoints}积分{reward.cashAmount?` · ${reward.cashAmount}元`:''}</p><small>{reward.description||'暂无说明'}</small></div><div className="stack-actions"><button className="secondary" disabled={!reward.active} onClick={()=>void requestReward(reward)}>申请兑换</button><button className="text-button" onClick={()=>{setEditing(reward);setForm({name:reward.name,category:reward.category,requiredPoints:reward.requiredPoints,cashAmount:reward.cashAmount??5,description:reward.description,active:reward.active});setModal(true)}}>编辑</button></div></article>):<p className="muted">还没有奖励，先由家长创建一个。</p>}</div></section><section className="panel"><div className="panel-head"><h2>兑换申请</h2></div><div className="card-list">{requests.length?requests.map(item=><article key={item.id}><div><strong>{item.rewardName}</strong><p>{item.requestedPoints}积分 · {item.status==='pending'?'待审批':item.status==='approved'?'已批准':'已拒绝'}</p></div>{item.status==='pending'&&<div className="stack-actions"><button className="primary" onClick={()=>void decide(item.id,'approve')}>批准</button><button className="secondary" onClick={()=>void decide(item.id,'reject')}>拒绝</button></div>}</article>):<p className="muted">还没有兑换申请。</p>}</div></section></div>
 {modal&&<div className="backdrop"><form className="modal" onSubmit={save}><div className="modal-head"><div><span className="eyebrow">Reward</span><h2>{editing?'编辑奖励':'新增奖励'}</h2></div><button className="icon-button" onClick={()=>setModal(false)} title="关闭" type="button"><X size={20}/></button></div><label>名称<input onChange={e=>setForm({...form,name:e.target.value})} required value={form.name}/></label><div className="form-row"><label>分类<select onChange={e=>setForm({...form,category:e.target.value})} value={form.category}>{rewardCategories.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label>所需积分<input min="1" onChange={e=>setForm({...form,requiredPoints:Number(e.target.value)})} type="number" value={form.requiredPoints}/></label></div>{form.category==='cash'&&<p className="muted">现金按 100 积分兑换 5 元，将自动按 {form.requiredPoints*5/100} 元保存。</p>}<label>说明<textarea onChange={e=>setForm({...form,description:e.target.value})} rows={3} value={form.description}/></label><label className="check-inline"><input checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})} type="checkbox"/>启用中</label><div className="modal-actions"><button className="secondary" onClick={()=>setModal(false)} type="button">取消</button><button className="primary" type="submit">保存奖励</button></div></form></div>}</>
}
