import { useEffect,useMemo,useRef,useState } from 'react';import { ArrowDown,ArrowUp,Clock3,GripVertical } from 'lucide-react';import { api } from '../api';import { isoDate } from '../dates';import { subjectLabel,subjects,type DailyTask,type Subject } from '../types';
export function TodayBoardPage({studentId}:{studentId:number}){const[date,setDate]=useState(isoDate()),[tasks,setTasks]=useState<DailyTask[]>([]),[filter,setFilter]=useState<Subject|'all'>('all'),[dragged,setDragged]=useState<number|null>(null),[error,setError]=useState(''),requestVersion=useRef(0);async function load(){const version=++requestVersion.current;try{const result=await api<{tasks:DailyTask[]}>(`/api/students/${studentId}/daily-plan/generate`,{method:'POST',body:JSON.stringify({date})});if(version===requestVersion.current)setTasks(result.tasks)}catch(reason){setError(reason instanceof Error?reason.message:'读取失败')}}useEffect(()=>{void load()},[studentId,date]);const visible=useMemo(()=>filter==='all'?tasks:tasks.filter(task=>task.subject===filter),[tasks,filter]);
 async function persist(next:DailyTask[]){const version=++requestVersion.current;setTasks(next);try{const result=await api<{tasks:DailyTask[]}>('/api/daily-tasks/order',{method:'PUT',body:JSON.stringify({studentId,date,orderedIds:next.map(task=>task.id)})});if(version===requestVersion.current)setTasks(result.tasks)}catch(reason){setError(reason instanceof Error?reason.message:'排序保存失败');await load()}}
 function reorderVisible(fromId:number,toId:number){if(fromId===toId)return;const ids=visible.map(task=>task.id),from=ids.indexOf(fromId),to=ids.indexOf(toId);if(from<0||to<0)return;ids.splice(to,0,...ids.splice(from,1));const reordered=ids.map(id=>tasks.find(item=>item.id===id)!);let cursor=0;const next=tasks.map(task=>filter==='all'||task.subject===filter?reordered[cursor++]:task);void persist(next)}
 function move(id:number,offset:number){const index=visible.findIndex(task=>task.id===id),target=visible[index+offset];if(target)reorderVisible(id,target.id)}
 return <><div className="page-heading"><div><span className="eyebrow">Today's Board</span><h1>今日看板</h1><p>按执行顺序完成任务；切换科目不会改变完整清单中的相对位置。</p></div><label className="date-control">执行日期<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div>{error&&<p className="error">{error}</p>}<div className="board-layout"><aside className="subject-filter"><strong>科目筛选</strong><button className={filter==='all'?'selected':''} onClick={()=>setFilter('all')}><span className="subject-dot all"/>全部任务 <em>{tasks.length}</em></button>{subjects.map(subject=><button className={filter===subject.id?'selected':''} key={subject.id} onClick={()=>setFilter(subject.id)}><span className={`subject-dot ${subject.id}`}/>{subject.label}<em>{tasks.filter(task=>task.subject===subject.id).length}</em></button>)}</aside><section className="board-main"><div className="board-summary"><div><strong>{visible.length}</strong><span>当前任务</span></div><div><strong>{visible.reduce((sum,t)=>sum+t.suggestedDuration,0)}</strong><span>计划分钟</span></div><div><strong>{visible.reduce((sum,t)=>sum+t.basePoints,0)}</strong><span>预计积分</span></div></div><div className="execution-list">{visible.length?visible.map((task,index)=><article draggable className={`execution-task subject-${task.subject}`} key={task.id} onDragStart={()=>setDragged(task.id)} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(dragged)reorderVisible(dragged,task.id);setDragged(null)}}><GripVertical className="drag-handle" size={20}/><span className="order-number">{String(index+1).padStart(2,'0')}</span><div className="task-copy"><span className="subject-badge">{subjectLabel(task.subject)}</span><h3>{task.content}</h3><p>{task.completionStandard}</p><div className="task-meta"><span><Clock3 size={14}/>{task.suggestedDuration}分钟</span><span>{task.basePoints}积分</span><span>未开始</span></div></div><div className="order-actions"><button disabled={index===0} onClick={()=>move(task.id,-1)} title="上移"><ArrowUp size={16}/></button><button disabled={index===visible.length-1} onClick={()=>move(task.id,1)} title="下移"><ArrowDown size={16}/></button></div></article>):<div className="empty-board"><h2>今天还没有任务</h2><p>请先在周计划中为这一天添加任务，系统会自动生成今日清单。</p></div>}</div></section></div></>}




