import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { App } from './App';
import './styles.css';
import './rubric.css';
import './material-cards.css';
import './week-execution.css';
import './today-board.css';
import './date-field.css';
import './student-switcher.css';
import './rewards.css';
import './dashboard.css';
import './live-clock.css';
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
